// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZTBbFdgSGxruQEmEcPMoN_rBNa0Gs6xY',
    appId: '1:250215316087:web:063c86319b1188fb68a472',
    messagingSenderId: '250215316087',
    projectId: 'instagram-17cdb',
    authDomain: 'instagram-17cdb.firebaseapp.com',
    storageBucket: 'instagram-17cdb.appspot.com',
    measurementId: 'G-JJJQDC6SC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpf2rb23QvVy0vZn7u2ISFcjXesGSU3sM',
    appId: '1:250215316087:android:3b8b33903142835568a472',
    messagingSenderId: '250215316087',
    projectId: 'instagram-17cdb',
    storageBucket: 'instagram-17cdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnBYIXZ8hjqTNpr4x7-LHTyWz-gNYNves',
    appId: '1:250215316087:ios:050dc4b74a2ed10568a472',
    messagingSenderId: '250215316087',
    projectId: 'instagram-17cdb',
    storageBucket: 'instagram-17cdb.appspot.com',
    iosBundleId: 'com.example.instagram',
  );
}
